### ISSUE TITLE
请问，我在 Swift 项目中使用遇到些问题能否提供帮助

### ISSUE THREAD

**Issue by ReverseScale** [WeijunDeng/Zabel#3]
我执行
`zabel xcodebuild -configuration "Release" -workspace "BinarySwiftDemo.xcworkspace" -scheme "BinarySwiftDemoBinary" -sdk iphoneo`
结果：
```
rm -rf Pods/*.xcodeproj/project.zabel_backup_pbxproj
rm -rf Pods/*.xcodeproj/*.zabel_target_context.yml
Traceback (most recent call last):
	10: from /Users/tim.xie/.rvm/rubies/ruby-2.7.2/bin/ruby_executable_hooks:22:in `<main>'
	 9: from /Users/tim.xie/.rvm/rubies/ruby-2.7.2/bin/ruby_executable_hooks:22:in `eval'
	 8: from /Users/tim.xie/.rvm/rubies/ruby-2.7.2/bin/zabel:23:in `<main>'
	 7: from /Users/tim.xie/.rvm/rubies/ruby-2.7.2/bin/zabel:23:in `load'
	 6: from /Users/tim.xie/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/zabel-1.0.4/bin/zabel:18:in `<top (required)>'
	 5: from /Users/tim.xie/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/zabel-1.0.4/lib/zabel.rb:709:in `zabel_pre'
	 4: from /Users/tim.xie/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/zabel-1.0.4/lib/zabel.rb:79:in `zabel_get_projects'
	 3: from /Users/tim.xie/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/xcodeproj-1.21.0/lib/xcodeproj/project.rb:113:in `open'
	 2: from /Users/tim.xie/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/xcodeproj-1.21.0/lib/xcodeproj/project.rb:211:in `initialize_from_file'
	 1: from /Users/tim.xie/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/xcodeproj-1.21.0/lib/xcodeproj/plist.rb:19:in `read_from_path'
/Users/tim.xie/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/xcodeproj-1.21.0/lib/xcodeproj/plist.rb:19:in `read': Permission denied @ rb_sysopen - /Users/tim.xie/GitHub/Tools/CocoaPodsSwiftBinary/Example/Pods/Pods.xcodeproj/project.pbxproj (Errno::EACCES)
```

如果可以能提供个 Demo 吗，非常感谢。

**Comment by WeijunDeng** [comment]
Demo 可以查看 https://github.com/WeijunDeng/Zabel/tree/main/test/case/simple
