### ISSUE TITLE
`glob': Operation not permitted

### ISSUE THREAD

**Issue by faimin** [WeijunDeng/Zabel#4]
```ruby
12:54:04 /Library/Ruby/Gems/2.6.0/gems/zabel-1.0.4/lib/zabel.rb:122:in `glob': Operation not permitted - /Library/Application Support/com.apple.TCC (Errno::EPERM)
12:54:04 	from /Library/Ruby/Gems/2.6.0/gems/zabel-1.0.4/lib/zabel.rb:122:in `zabel_get_dependency_files'
12:54:04 	from /Library/Ruby/Gems/2.6.0/gems/zabel-1.0.4/lib/zabel.rb:470:in `block (2 levels) in zabel_post'
12:54:04 	from /Library/Ruby/Gems/2.6.0/gems/zabel-1.0.4/lib/zabel.rb:455:in `each'
12:54:04 	from /Library/Ruby/Gems/2.6.0/gems/zabel-1.0.4/lib/zabel.rb:455:in `block in zabel_post'
12:54:04 	from /Library/Ruby/Gems/2.6.0/gems/zabel-1.0.4/lib/zabel.rb:449:in `each'
12:54:04 	from /Library/Ruby/Gems/2.6.0/gems/zabel-1.0.4/lib/zabel.rb:449:in `zabel_post'
12:54:04 	from /Library/Ruby/Gems/2.6.0/gems/zabel-1.0.4/bin/zabel:24:in `<top (required)>'
12:54:04 	from /usr/local/bin/zabel:23:in `load'
12:54:04 	from /usr/local/bin/zabel:23:in `<main>'

```

请问这个权限不足是`zabel`的问题还是我的问题？

**Comment by WeijunDeng** [comment]
@faimin 使用 1.0.5 试试

**Comment by faimin** [comment]
`1.0.5` 版本不报错了
